name = "roadwork-blackroad"
main = "src/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
[[routes]]
pattern = "roadwork.blackroad.io/*"
zone_name = "blackroad.io"
[vars]
ENVIRONMENT = "production"
SERVICE_NAME = "roadwork"
VERSION = "2.0.0"
[[kv_namespaces]]
binding = "STORE"
id = "e37a7a608c4e424cb26c0cd4425fe6af"
[ai]
binding = "AI"
[[d1_databases]]
binding = "DB"
database_name = "blackroad-os-main"
database_id = "e2c6dcd9-c21a-48ac-8807-7b3a6881c4f7"
